# GoReleaser configuration for terraform-provider-insightfinder
# Visit https://goreleaser.com for documentation

version: 2

before:
  hooks:
    # Ensure go.mod is tidy
    - go mod tidy

builds:
  - env:
      # CGO must be disabled for reproducible builds
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      # Use your GPG key ID for signing
      # Set the GPG_FINGERPRINT environment variable
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## InsightFinder Provider {{ .Tag }} ({{ .Date }})
    
    Release notes for version {{ .Tag }}.
  footer: |
    ## Installation
    
    ### Terraform Registry
    
    ```hcl
    terraform {
      required_providers {
        insightfinder = {
          source  = "insightfinder/insightfinder"
          version = "~> {{ .Version }}"
        }
      }
    }
    ```
    
    ### Manual Installation
    
    Download the appropriate binary for your platform from the assets below and follow the [installation instructions](https://github.com/insightfinder/terraform-provider-insightfinder#installation).

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'README'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Enhancements'
      regexp: '^.*?enhancement(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Documentation'
      regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Other
      order: 999

# Terraform-specific configuration
# This section is used by the Terraform Registry
metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
