// Copyright (c) InsightFinder Inc.
// SPDX-License-Identifier: MPL-2.0

package client

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// slackServiceHost is the fixed service_host value InsightFinder uses for Slack integrations.
const slackServiceHost = "SLACK"

// SlackProjectRule represents an optional match rule for a per-project Slack override.
type SlackProjectRule struct {
	Type    string `json:"type,omitempty"`
	Keyword string `json:"keyword,omitempty"`
}

// SlackProjectConfig represents a per-project Slack notification override.
type SlackProjectConfig struct {
	ProjectName                   string            `json:"projectName"`
	Channel                       string            `json:"channel"`
	Webhook                       string            `json:"webhook"`
	Options                       []string          `json:"options"`
	Rule                          *SlackProjectRule `json:"rule,omitempty"`
	EnableConsolidationInfoUpdate bool              `json:"enableConsolidationInfoUpdate"`
	PriorityLevels                []int64           `json:"priorityLevels"`
}

// SlackConfig represents a single Slack integration for one system.
// Account is generated by the API and is empty until the integration has been created.
type SlackConfig struct {
	Account        string
	SystemID       string
	WebHook        string
	ChannelName    string
	Options        []string
	ProjectConfigs []SlackProjectConfig
}

// listSlackEntries fetches all raw Slack external-service entries for the customer.
func (c *Client) listSlackEntries() ([]map[string]interface{}, error) {
	params := url.Values{}
	params.Add("serviceProvider", "Slack")
	params.Add("tzOffset", "-14400000")

	path := fmt.Sprintf("/api/external/v1/system/externalServlies/list?%s", params.Encode())
	body, statusCode, err := c.DoRequest("GET", path, nil)
	if err != nil {
		return nil, err
	}

	if statusCode == 404 || statusCode == 204 {
		return nil, nil
	}
	if statusCode != 200 {
		return nil, fmt.Errorf("failed to list Slack integrations: HTTP %d", statusCode)
	}

	var response struct {
		ExtServiceAllInfo []map[string]interface{} `json:"extServiceAllInfo"`
		Success           bool                     `json:"success"`
		Message           string                   `json:"message"`
	}
	if err := json.Unmarshal(body, &response); err != nil {
		return nil, fmt.Errorf("failed to parse response: %w", err)
	}
	if !response.Success {
		return nil, nil
	}

	entries := make([]map[string]interface{}, 0, len(response.ExtServiceAllInfo))
	for _, entry := range response.ExtServiceAllInfo {
		provider, _ := entry["serviceProvider"].(string)
		if strings.EqualFold(strings.TrimSpace(provider), "Slack") {
			entries = append(entries, entry)
		}
	}
	return entries, nil
}

// parseSlackProjectConfigs converts a raw projectConfigs JSON array into typed structs.
func parseSlackProjectConfigs(raw []interface{}) []SlackProjectConfig {
	result := make([]SlackProjectConfig, 0, len(raw))
	for _, v := range raw {
		pcMap, ok := v.(map[string]interface{})
		if !ok {
			continue
		}
		pc := SlackProjectConfig{}
		if s, ok := pcMap["projectName"].(string); ok {
			pc.ProjectName = s
		}
		if s, ok := pcMap["channel"].(string); ok {
			pc.Channel = s
		}
		if s, ok := pcMap["webhook"].(string); ok {
			pc.Webhook = s
		}
		if opts, ok := pcMap["options"].([]interface{}); ok {
			for _, o := range opts {
				if s, ok := o.(string); ok {
					pc.Options = append(pc.Options, s)
				}
			}
		}
		if b, ok := pcMap["enableConsolidationInfoUpdate"].(bool); ok {
			pc.EnableConsolidationInfoUpdate = b
		}
		if levels, ok := pcMap["priorityLevels"].([]interface{}); ok {
			for _, l := range levels {
				if f, ok := l.(float64); ok {
					pc.PriorityLevels = append(pc.PriorityLevels, int64(f))
				}
			}
		}
		if ruleMap, ok := pcMap["rule"].(map[string]interface{}); ok {
			rule := &SlackProjectRule{}
			if s, ok := ruleMap["type"].(string); ok {
				rule.Type = s
			}
			if s, ok := ruleMap["keyword"].(string); ok {
				rule.Keyword = s
			}
			pc.Rule = rule
		}
		result = append(result, pc)
	}
	return result
}

// parseSlackEntry converts a raw externalServlies entry into a SlackConfig.
func parseSlackEntry(entry map[string]interface{}) *SlackConfig {
	config := &SlackConfig{}
	if s, ok := entry["account"].(string); ok {
		config.Account = s
	}
	if s, ok := entry["systemId"].(string); ok {
		config.SystemID = s
	}
	if s, ok := entry["channelName"].(string); ok {
		config.ChannelName = s
	}
	if s, ok := entry["webHook"].(string); ok {
		config.WebHook = s
	}
	if optionsStr, ok := entry["options"].(string); ok && optionsStr != "" {
		var options []string
		if err := json.Unmarshal([]byte(optionsStr), &options); err == nil {
			config.Options = options
		}
	}
	if configsStr, ok := entry["configs"].(string); ok && configsStr != "" {
		var configs map[string]interface{}
		if err := json.Unmarshal([]byte(configsStr), &configs); err == nil {
			if pcRaw, ok := configs["projectConfigs"].([]interface{}); ok {
				config.ProjectConfigs = parseSlackProjectConfigs(pcRaw)
			}
		}
	}
	return config
}

// GetSlackConfig retrieves a single Slack integration by its generated account ID.
// Returns nil, nil if the integration no longer exists.
func (c *Client) GetSlackConfig(account string) (*SlackConfig, error) {
	entries, err := c.listSlackEntries()
	if err != nil {
		return nil, err
	}
	for _, entry := range entries {
		entryAccount, _ := entry["account"].(string)
		if strings.EqualFold(strings.TrimSpace(entryAccount), strings.TrimSpace(account)) {
			return parseSlackEntry(entry), nil
		}
	}
	return nil, nil
}

// normalizeSlackProjectConfigs ensures list-typed fields marshal as JSON arrays ("[]") rather than null.
func normalizeSlackProjectConfigs(configs []SlackProjectConfig) []SlackProjectConfig {
	normalized := make([]SlackProjectConfig, len(configs))
	for i, pc := range configs {
		if pc.Options == nil {
			pc.Options = []string{}
		}
		if pc.PriorityLevels == nil {
			pc.PriorityLevels = []int64{}
		}
		normalized[i] = pc
	}
	return normalized
}

// buildSlackFormData builds the shared form fields for create/update requests.
func buildSlackFormData(config *SlackConfig, username string) (url.Values, error) {
	options := config.Options
	if options == nil {
		options = []string{}
	}
	optionsJSON, err := json.Marshal(options)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal options: %w", err)
	}

	systemKey := map[string]string{
		"userName":   username,
		"systemName": config.SystemID,
		"envName":    "All",
	}
	systemKeyJSON, err := json.Marshal(systemKey)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal systemKey: %w", err)
	}

	formData := url.Values{}
	formData.Set("operation", "Slack")
	formData.Set("webHook", config.WebHook)
	formData.Set("channelName", config.ChannelName)
	formData.Set("options", string(optionsJSON))
	formData.Set("systemKey", string(systemKeyJSON))
	formData.Set("customerName", username)

	if len(config.ProjectConfigs) > 0 {
		projectConfigsJSON, err := json.Marshal(normalizeSlackProjectConfigs(config.ProjectConfigs))
		if err != nil {
			return nil, fmt.Errorf("failed to marshal project configs: %w", err)
		}
		formData.Set("projectConfigs", string(projectConfigsJSON))
	}

	return formData, nil
}

// CreateSlackConfig creates a new Slack integration and returns the API-generated account ID.
//
// If an integration already exists for this exact system + webhook + channel (e.g. it was
// created outside Terraform, or state was lost/reinitialized), that existing integration is
// adopted and brought in line with config instead of creating a duplicate.
//
// Otherwise, the create API does not return the new account ID directly, so the newly created
// entry is identified by diffing the set of account IDs for this system before and after the call.
func (c *Client) CreateSlackConfig(config *SlackConfig, username string) (string, error) {
	existingAccount, found, err := c.findSlackAccount(config.SystemID, username, config.WebHook, config.ChannelName)
	if err != nil {
		return "", fmt.Errorf("failed to check for an existing Slack integration: %w", err)
	}
	if found {
		if err := c.applySlackUpdate(existingAccount, config, username); err != nil {
			return "", err
		}
		return existingAccount, nil
	}

	before, err := c.listSlackEntries()
	if err != nil {
		return "", err
	}
	existing := make(map[string]bool, len(before))
	for _, entry := range before {
		systemID, _ := entry["systemId"].(string)
		if systemID != config.SystemID {
			continue
		}
		if account, _ := entry["account"].(string); account != "" {
			existing[account] = true
		}
	}

	formData, err := buildSlackFormData(config, username)
	if err != nil {
		return "", err
	}

	path := "/api/external/v1/service-integration?tzOffset=-14400000"
	body, statusCode, err := c.DoFormRequest("POST", path, formData)
	if err != nil {
		return "", err
	}
	if statusCode != 200 {
		return "", fmt.Errorf("failed to create Slack integration: HTTP %d - %s", statusCode, string(body))
	}

	var response ServiceNowResponse
	if err := json.Unmarshal(body, &response); err == nil && !response.Success {
		msg := response.Message
		if msg == "" {
			msg = "unknown error"
		}
		return "", fmt.Errorf("Slack integration creation failed: %s", msg)
	}

	after, err := c.listSlackEntries()
	if err != nil {
		return "", err
	}

	var candidates []map[string]interface{}
	for _, entry := range after {
		systemID, _ := entry["systemId"].(string)
		account, _ := entry["account"].(string)
		if systemID == config.SystemID && account != "" && !existing[account] {
			candidates = append(candidates, entry)
		}
	}

	if len(candidates) == 0 {
		return "", fmt.Errorf("Slack integration was created but the new entry could not be located to determine its account ID")
	}
	if len(candidates) == 1 {
		account, _ := candidates[0]["account"].(string)
		return account, nil
	}

	// Multiple new entries appeared concurrently; narrow down by matching webhook + channel.
	for _, entry := range candidates {
		webHook, _ := entry["webHook"].(string)
		channelName, _ := entry["channelName"].(string)
		if webHook == config.WebHook && channelName == config.ChannelName {
			account, _ := entry["account"].(string)
			return account, nil
		}
	}

	account, _ := candidates[0]["account"].(string)
	return account, nil
}

// findSlackAccount locates the account ID of an existing Slack integration by matching on
// system ID, username, webhook, and channel name — mirroring how the InsightFinder UI
// resolves which integration to update before calling update-ext-service, rather than
// trusting a previously stored account ID. found is false (with a nil error) when no
// matching integration exists; err is only non-nil when the lookup itself failed.
func (c *Client) findSlackAccount(systemID, username, webHook, channelName string) (account string, found bool, err error) {
	entries, err := c.listSlackEntries()
	if err != nil {
		return "", false, err
	}

	for _, entry := range entries {
		entrySystemID, _ := entry["systemId"].(string)
		entryUserName, _ := entry["userName"].(string)
		entryWebHook, _ := entry["webHook"].(string)
		entryChannelName, _ := entry["channelName"].(string)

		if entrySystemID == systemID &&
			strings.EqualFold(strings.TrimSpace(entryUserName), strings.TrimSpace(username)) &&
			entryWebHook == webHook &&
			entryChannelName == channelName {
			if acc, _ := entry["account"].(string); acc != "" {
				return acc, true, nil
			}
		}
	}

	return "", false, nil
}

// doSlackLicenseKeyFormRequest performs a form-encoded HTTP request authenticated via
// X-User-Name/X-License-Key headers. update-ext-service-by-licenseKey (unlike the other Slack
// endpoints) rejects the X-API-Key header used elsewhere. Parameters are sent in the request
// body rather than the URL query string — with many project_configs entries the query-string
// form of this request can exceed the server's URI length limit (HTTP 414).
func (c *Client) doSlackLicenseKeyFormRequest(method, path string, formData url.Values) ([]byte, int, error) {
	reqURL := fmt.Sprintf("%s%s", c.BaseURL, path)
	req, err := http.NewRequest(method, reqURL, strings.NewReader(formData.Encode()))
	if err != nil {
		return nil, 0, fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("X-User-Name", c.Username)
	req.Header.Set("X-License-Key", c.LicenseKey)
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, resp.StatusCode, fmt.Errorf("failed to read response body: %w", err)
	}

	return respBody, resp.StatusCode, nil
}

// applySlackUpdate pushes config onto an already-identified Slack integration account via the
// update-ext-service-by-licenseKey API.
func (c *Client) applySlackUpdate(account string, config *SlackConfig, username string) error {
	options := config.Options
	if options == nil {
		options = []string{}
	}
	optionsJSON, err := json.Marshal(options)
	if err != nil {
		return fmt.Errorf("failed to marshal options: %w", err)
	}

	systemKey := map[string]string{
		"userName":   username,
		"systemName": config.SystemID,
		"envName":    "All",
	}
	systemKeyJSON, err := json.Marshal(systemKey)
	if err != nil {
		return fmt.Errorf("failed to marshal systemKey: %w", err)
	}

	projectConfigsJSON, err := json.Marshal(normalizeSlackProjectConfigs(config.ProjectConfigs))
	if err != nil {
		return fmt.Errorf("failed to marshal project configs: %w", err)
	}

	formData := url.Values{}
	formData.Set("operation", "Slack")
	formData.Set("account", account)
	formData.Set("webHook", config.WebHook)
	formData.Set("channelName", config.ChannelName)
	formData.Set("options", string(optionsJSON))
	formData.Set("systemKey", string(systemKeyJSON))
	formData.Set("userName", username)
	formData.Set("projectConfigs", string(projectConfigsJSON))

	path := "/api/v2/update-ext-service-by-licenseKey"
	body, statusCode, err := c.doSlackLicenseKeyFormRequest("POST", path, formData)
	if err != nil {
		return err
	}
	if statusCode != 200 {
		return fmt.Errorf("failed to update Slack integration: HTTP %d - %s", statusCode, string(body))
	}

	var response ServiceNowResponse
	if err := json.Unmarshal(body, &response); err == nil && !response.Success {
		msg := response.Message
		if msg == "" {
			msg = "unknown error"
		}
		return fmt.Errorf("Slack integration update failed: %s", msg)
	}

	return nil
}

// UpdateSlackConfig updates an existing Slack integration in place.
//
// The integration to update is first located by matching oldSystemID, oldWebHook, and
// oldChannelName (the integration's identity before this update) against the list of existing
// integrations, and the resulting account ID is then used to apply newConfig via the
// update-ext-service API. Returns the matched account ID so callers can keep it in sync.
func (c *Client) UpdateSlackConfig(oldSystemID, oldWebHook, oldChannelName string, newConfig *SlackConfig, username string) (string, error) {
	account, found, err := c.findSlackAccount(oldSystemID, username, oldWebHook, oldChannelName)
	if err != nil {
		return "", err
	}
	if !found {
		return "", fmt.Errorf("no existing Slack integration found matching system, username, webhook, and channel")
	}

	if err := c.applySlackUpdate(account, newConfig, username); err != nil {
		return "", err
	}

	return account, nil
}

// DeleteSlackConfig removes a Slack integration identified by its account ID.
func (c *Client) DeleteSlackConfig(account, username string) error {
	serviceID := fmt.Sprintf("Slack:%s:%s", account, slackServiceHost)

	formData := url.Values{}
	formData.Set("serviceProvider", "Slack")
	formData.Set("operation", "delete")
	formData.Set("service_id", serviceID)
	formData.Set("serviceOwner", username)
	formData.Set("customerName", username)

	path := "/api/external/v1/service-integration?tzOffset=-14400000"
	body, statusCode, err := c.DoFormRequest("POST", path, formData)
	if err != nil {
		return err
	}

	if statusCode != 200 && statusCode != 404 {
		return fmt.Errorf("failed to delete Slack integration: HTTP %d - %s", statusCode, string(body))
	}

	return nil
}
